name: Update CHANGELOG

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., 0.1.0)'
        required: true
        type: string
      old_version:
        description: 'Previous version (e.g., 0.0.1)'
        required: true
        type: string

jobs:
  update_changelog:
    name: Generate and commit CHANGELOG
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install git-cliff
        run: bun x --bun git-cliff --version

      - name: Generate CHANGELOG
        run: |
          bun x --bun git-cliff --tag v${{ github.event.inputs.version }} -o CHANGELOG.md

      - name: Commit CHANGELOG
        run: |
          git add CHANGELOG.md
          git commit -m "docs: update CHANGELOG for v${{ github.event.inputs.version }}"
          git push origin main

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.event.inputs.version }}
          release_name: v${{ github.event.inputs.version }}
          body: |
            Release v${{ github.event.inputs.version }}
            Previous: v${{ github.event.inputs.old_version }}
          draft: false
          prerelease: false
