name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  check-changes:
    name: Check if code changed
    runs-on: ubuntu-latest
    outputs:
      code-changed: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            code:
              - 'packages/!(website)/src/**'
              - '.github/workflows/**'
              - 'package.json'
              - 'tsconfig.json'
              - 'bun.lock'
              - 'biome.json'

  test:
    name: Test & Build
    needs: check-changes
    if: needs.check-changes.outputs.code-changed == 'true'
    uses: ./.github/workflows/test.yml

  success:
    name: All checks passed
    runs-on: ubuntu-latest
    needs: [check-changes, test]
    if: always()
    steps:
      - name: Report status
        run: |
          if [[ "${{ needs.check-changes.outputs.code-changed }}" == "true" ]]; then
            if [[ "${{ needs.test.result }}" == "success" ]]; then
              echo "✓ Code changed - all tests passed"
            else
              echo "✗ Code changed - tests failed"
              exit 1
            fi
          else
            echo "✓ No code changes - skipped tests"
          fi
