name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  test:
    name: Test & Lint
    uses: ./.github/workflows/test.yml

  build:
    name: Build
    needs: test
    uses: ./.github/workflows/build.yml
