name: Docs

on:
  push:
    branches: [develop, main]
    paths:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [develop, main]
    paths:
      - 'docs/**'
      - '**.md'

jobs:
  validate:
    name: Validate Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate markdown
        run: |
          # Basic markdown validation - check for broken links, syntax errors
          find docs -name "*.md" -type f | while read file; do
            echo "Checking $file"
            # Simple check: ensure file isn't empty
            if [ ! -s "$file" ]; then
              echo "ERROR: $file is empty"
              exit 1
            fi
          done
          echo "✓ All markdown files validated"
